name: coopa
description: A new Flutter project.

# Set publish_to to 'none' to prevent accidental publishing to pub.dev
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

# Set the minimum SDK version required for the project
environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Dependencies for the project's UI and functionality
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  font_awesome_flutter: ^10.4.0
  cached_network_image: ^3.2.3
  flutter_switch: ^0.3.2
  image_picker: ^0.8.7
  share: ^2.0.4
  sliding_up_panel: ^2.0.0+1
  flutter_svg: ^2.0.3
  flutter_staggered_grid_view: ^0.6.2
  shimmer: ^2.0.0

  # Dependencies for Firebase integration
  firebase_core: ^2.5.0
  firebase_auth: ^4.2.6
  firebase_storage: ^11.0.11
  google_sign_in: ^5.4.4
  cloud_firestore: ^4.3.2
  firebase_database: ^10.0.14
  firebase_messaging: ^14.3.0
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  fluttertoast: ^8.2.1
  open_street_map_search_and_pick: ^0.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting package for maintaining code quality
  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:

  # Use material design widgets
  uses-material-design: true

  # Add assets to the project
  assets:
    - assets/images/
    - assets/font/
    - assets/icons/

  # Example configuration for custom fonts
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
